spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/db_user
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  data:
#    mongodb:
#      host: 192.168.56.10
#      port: 27017
#      database: user
#      username: root
#      password: "123456"
#      authentication-database: admin
#
#logging:
#  level:
#    org.springframework.data.mongodb.core: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
server:
  port: 8088
