spring:
  application:
    name: article
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/db_blog
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8089
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
